### ISSUE TITLE
写的很不错，也看懂了，但是一些场景还是写不出来，求教

### ISSUE THREAD

**Issue by scsfwgy** [cdoco/learn-regex-zh#11]
[strings_temp2.txt](https://github.com/cdoco/learn-regex-zh/files/6767288/strings_temp2.txt)

匹配最下面字符串内容：

匹配示例：
1.  ``<string name="app_name" >测试应用</string>``
2. ``<string    name="key1">测试内容</string>``

以下都要匹配上，总计匹配上五个。

我写了以下正则：
``<string[ ]*name="(.*)"[ ]*>(.)*</string>`` 除了带换行那个都ok
``<string[ ]*name="(.*)"[ ]*>(.\n)*</string>`` 无任何效果

~~

![image](https://user-images.githubusercontent.com/16045179/124541895-effebb80-de54-11eb-9e35-ad9908d0f2d0.png)

~~

**Comment by Higurashi-kagome** [comment]
试试 `<string\s*name="(.*)"\s*>((?!</string>)[\s\S\n])*</string>`。

**Comment by scsfwgy** [comment]
感谢！！！确实想到了在断言这一块下手，还是写不出来。

**Comment by scsfwgy** [comment]
待匹配：``String d = "我是 文案" + "我是+拼接 文案"; ``
要求匹配出：1.我是 文案 2.我是+拼接 文案
我写出：``(?<=")((?!")(.))*(?=")`` ,结果匹配出三个结果：1.我是 文案 2.+  3.我是+拼接 文案

@Higurashi-kagome 有时间帮忙看一下，怎么处理？

**Comment by Higurashi-kagome** [comment]
试试 `(?<=")((?!(\s\+\s|")).)*(?=")`。

**Comment by scsfwgy** [comment]
> 试试 `(?<=")((?!(\s\+\s|")).)*(?=")`。

在你的基础上改了一下，可以了：``(?<=")((?!(\s*\+\s*")).)*(?=")``  String d="xx"+"yy" +左右可以有任意空格，也可以没有。
感谢
